import {
  AlignmentType,
  Document,
  HeadingLevel,
  Packer,
  Paragraph,
  TextRun,
} from "docx";
import type { RenderDoc, RenderNode } from "./ir.js";

const HEADING_BY_LEVEL: Record<number, (typeof HeadingLevel)[keyof typeof HeadingLevel]> = {
  1: HeadingLevel.HEADING_1,
  2: HeadingLevel.HEADING_2,
  3: HeadingLevel.HEADING_3,
  4: HeadingLevel.HEADING_4,
  5: HeadingLevel.HEADING_5,
  6: HeadingLevel.HEADING_6,
};

export async function renderDocx(doc: RenderDoc): Promise<Buffer> {
  const children: Paragraph[] = [];

  children.push(
    new Paragraph({
      text: doc.title,
      heading: HeadingLevel.TITLE,
      alignment: AlignmentType.CENTER,
    }),
    new Paragraph({
      text: doc.subtitle,
      alignment: AlignmentType.CENTER,
      spacing: { after: 240 },
    }),
    new Paragraph({
      text: "Document control",
      heading: HeadingLevel.HEADING_2,
    }),
  );

  for (const node of doc.cover) {
    walk(node, children);
  }

  for (const node of doc.body) {
    walk(node, children);
  }

  children.push(
    new Paragraph({
      text: `Generated by actcheck ${doc.toolVersion} on ${doc.generatedAt}.`,
      spacing: { before: 320 },
      alignment: AlignmentType.CENTER,
    }),
  );
  if (doc.retention) {
    children.push(
      new Paragraph({
        text: `Article 18(1) retention obligation: ${doc.retention.placedOnMarket} → ${doc.retention.retentionUntil}.`,
        alignment: AlignmentType.CENTER,
      }),
    );
  }

  const docxFile = new Document({
    creator: "actcheck",
    title: doc.title,
    description: doc.subtitle,
    sections: [
      {
        children,
      },
    ],
  });

  return Buffer.from(await Packer.toBuffer(docxFile));
}

function walk(node: RenderNode, out: Paragraph[]): void {
  switch (node.kind) {
    case "section": {
      out.push(
        new Paragraph({
          text: node.title,
          heading: HEADING_BY_LEVEL[Math.min(6, Math.max(1, node.level))],
        }),
      );
      for (const child of node.children) walk(child, out);
      break;
    }
    case "paragraph":
      out.push(new Paragraph({ children: [new TextRun(node.text)] }));
      break;
    case "list": {
      for (const item of node.items) {
        out.push(new Paragraph({ children: [new TextRun(item)] }));
      }
      break;
    }
    case "labelled": {
      for (const p of node.pairs) {
        out.push(
          new Paragraph({
            children: [
              new TextRun({ text: `${p.label}: `, bold: true }),
              new TextRun(p.value),
            ],
          }),
        );
      }
      break;
    }
  }
}
