import type { RenderDoc, RenderNode } from "./ir.js";

export function renderHtml(doc: RenderDoc): string {
  const head = `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<meta name="generator" content="actcheck ${esc(doc.toolVersion)}" />
<title>${esc(doc.title)} — ${esc(doc.subtitle)}</title>
<style>
:root { --ink: #0b0c10; --paper: #fff; --muted: #5a6470; --accent: #1f4e79; --rule: #d9dde2; }
@media (prefers-color-scheme: dark) {
  :root { --ink: #e9eef5; --paper: #0b0c10; --muted: #98a3af; --accent: #6aa8ff; --rule: #2a313a; }
}
html, body { background: var(--paper); color: var(--ink); }
body { font-family: ui-sans-serif, system-ui, "Liberation Sans", "Helvetica Neue", Arial, sans-serif; line-height: 1.55; margin: 2rem auto; max-width: 48rem; padding: 0 1rem; }
header { border-bottom: 2px solid var(--accent); padding-bottom: 1rem; margin-bottom: 2rem; }
h1 { font-size: 1.75rem; margin: 0 0 .25rem; color: var(--accent); }
h2 { font-size: 1.25rem; margin-top: 2.5rem; border-bottom: 1px solid var(--rule); padding-bottom: .25rem; color: var(--accent); }
h3 { font-size: 1.05rem; margin-top: 1.5rem; }
h4 { font-size: .95rem; margin-top: 1.25rem; color: var(--muted); text-transform: uppercase; letter-spacing: .02em; }
h5, h6 { font-size: .9rem; margin-top: 1rem; }
p { margin: .5rem 0; }
ul.alpha-list { list-style: none; padding-left: 0; }
ul.alpha-list li { padding: .15rem 0; }
.cover { background: color-mix(in srgb, var(--accent) 6%, transparent); border: 1px solid var(--rule); border-radius: 8px; padding: 1rem 1.25rem; margin-bottom: 2rem; }
.cover dt { font-weight: 600; color: var(--muted); font-size: .8rem; text-transform: uppercase; letter-spacing: .03em; }
.cover dd { margin: 0 0 .5rem; font-size: 1rem; }
footer { margin-top: 3rem; padding-top: 1rem; border-top: 1px solid var(--rule); color: var(--muted); font-size: .85rem; }
@media print {
  body { margin: 1.5cm; max-width: none; }
  h2 { page-break-before: auto; }
}
</style>
</head>
<body>
<header>
<h1>${esc(doc.title)}</h1>
<div style="color: var(--muted);">${esc(doc.subtitle)}</div>
</header>
<section class="cover">
<dl>
${doc.cover.map(renderCoverNode).join("\n")}
</dl>
</section>
${doc.body.map((n) => renderNode(n)).join("\n")}
<footer>
Generated by actcheck ${esc(doc.toolVersion)} on ${esc(doc.generatedAt)}.
${
  doc.retention
    ? `Article 18(1) retention obligation: ${esc(doc.retention.placedOnMarket)} → ${esc(doc.retention.retentionUntil)}.`
    : ""
}
</footer>
</body>
</html>
`;
  return head;
}

function renderCoverNode(node: RenderNode): string {
  if (node.kind !== "labelled") return "";
  return node.pairs
    .map(
      (p) => `<dt>${esc(p.label)}</dt><dd>${esc(p.value)}</dd>`,
    )
    .join("\n");
}

function renderNode(node: RenderNode): string {
  switch (node.kind) {
    case "section": {
      const heading = `<h${headingLevel(node.level)}>${esc(node.title)}</h${headingLevel(node.level)}>`;
      return `${heading}\n${node.children.map(renderNode).join("\n")}`;
    }
    case "paragraph":
      return `<p>${esc(node.text)}</p>`;
    case "list": {
      const items = node.items
        .map((line) => `<li>${esc(line)}</li>`)
        .join("\n");
      return `<ul class="alpha-list">\n${items}\n</ul>`;
    }
    case "labelled":
      return `<dl>${node.pairs.map((p) => `<dt>${esc(p.label)}</dt><dd>${esc(p.value)}</dd>`).join("\n")}</dl>`;
  }
}

function headingLevel(level: number): number {
  return Math.min(6, Math.max(2, level));
}

function esc(s: string): string {
  return s
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}
