import { formatAlphaList } from "../formatter.js";
import {
  computeRetentionInfo,
  type RetentionInfo,
} from "../validator.js";

/** Intermediate representation produced from a parsed declaration. */
export type RenderNode =
  | { kind: "section"; title: string; level: number; children: RenderNode[] }
  | { kind: "paragraph"; text: string }
  | { kind: "list"; items: string[] }
  | { kind: "labelled"; pairs: Array<{ label: string; value: string }> };

export interface RenderDoc {
  title: string;
  subtitle: string;
  cover: RenderNode[];
  body: RenderNode[];
  toolVersion: string;
  generatedAt: string;
  retention?: RetentionInfo;
}

export interface BuildIrOptions {
  declaration: Record<string, unknown>;
  toolVersion: string;
  /** Optional override for "Generated by actcheck …" date — defaults to now. */
  generatedAt?: string;
}

// Top-level keys in declaration order with their human-facing section titles.
const ANNEX_IV_SECTIONS: Array<{ key: string; title: string }> = [
  { key: "general_description", title: "1 — General description of the AI system (Annex IV(1))" },
  { key: "development", title: "2 — Development process and design (Annex IV(2))" },
  { key: "monitoring", title: "3 — Monitoring, functioning, and control (Annex IV(3))" },
  { key: "performance_metrics", title: "4 — Performance metrics (Annex IV(4))" },
  { key: "risk_management", title: "5 — Risk management system (Annex IV(5))" },
  { key: "lifecycle_changes", title: "6 — Lifecycle changes (Annex IV(6))" },
  { key: "standards", title: "7 — Standards and specifications (Annex IV(7))" },
  { key: "declaration_of_conformity", title: "8 — EU declaration of conformity (Annex IV(8))" },
  { key: "post_market_monitoring", title: "9 — Post-market monitoring (Annex IV(9))" },
  { key: "product_harmonisation", title: "Article 11(2) — Product harmonisation framing" },
  { key: "simplified_documentation", title: "Article 11(1) — SME simplified documentation route" },
];

const ANNEX_XI_SECTIONS: Array<{ key: string; title: string }> = [
  { key: "general_description", title: "1.1 — General description (Annex XI Section 1.1)" },
  { key: "detailed_description", title: "1.2 — Detailed description (Annex XI Section 1.2)" },
  { key: "systemic_risk", title: "Section 2 — Additional documentation for systemic-risk models" },
];

export function buildIr(opts: BuildIrOptions): RenderDoc {
  const { declaration } = opts;
  const profile = detectProfile(declaration);
  const sections = profile === "annex-xi" ? ANNEX_XI_SECTIONS : ANNEX_IV_SECTIONS;
  const titleBase = profile === "annex-xi" ? "Annex XI" : "Annex IV";

  const cover = buildCover(declaration, titleBase);
  const body: RenderNode[] = [];

  for (const { key, title } of sections) {
    if (!(key in declaration) || declaration[key] == null) continue;
    body.push(renderTopLevelSection(title, declaration[key]));
  }

  const provider = (
    (declaration["general_description"] as Record<string, unknown>)
      ?.["provider"] as Record<string, unknown>
  )?.["name"];
  const systemName =
    ((declaration["declaration_of_conformity"] as Record<string, unknown>)
      ?.["system_name"] as string) ?? "AI system";

  return {
    title: `EU AI Act — ${titleBase} Technical Documentation`,
    subtitle: `${systemName}${provider ? ` · ${provider}` : ""}`,
    cover,
    body,
    toolVersion: opts.toolVersion,
    generatedAt: opts.generatedAt ?? new Date().toISOString(),
    retention: computeRetentionInfo(declaration),
  };
}

function detectProfile(decl: Record<string, unknown>): "annex-iv" | "annex-xi" {
  const meta = decl["actcheck"] as Record<string, unknown> | undefined;
  return meta?.["profile"] === "annex-xi" ? "annex-xi" : "annex-iv";
}

function buildCover(
  decl: Record<string, unknown>,
  titleBase: string,
): RenderNode[] {
  const pairs: Array<{ label: string; value: string }> = [];
  const gd = decl["general_description"] as Record<string, unknown> | undefined;
  const provider = (gd?.["provider"] as Record<string, unknown> | undefined)
    ?.["name"];
  const systemVersion = gd?.["system_version"];
  const intendedPurpose = gd?.["intended_purpose"];

  const rc = decl["risk_classification"] as Record<string, unknown> | undefined;
  const riskLevel = rc?.["risk_level"];
  const placed = rc?.["placed_on_market"];

  if (provider) pairs.push({ label: "Provider", value: String(provider) });
  if (systemVersion)
    pairs.push({ label: "System version", value: String(systemVersion) });
  if (intendedPurpose)
    pairs.push({ label: "Intended purpose", value: String(intendedPurpose) });
  if (riskLevel) pairs.push({ label: "Risk level", value: String(riskLevel) });
  if (placed)
    pairs.push({ label: "Placed on market", value: String(placed) });

  const retention = computeRetentionInfo(decl);
  if (retention) {
    pairs.push({
      label: "Retention until (Art 18(1))",
      value: retention.retentionUntil,
    });
  }

  pairs.push({ label: "Documentation type", value: `${titleBase} technical documentation` });

  return [{ kind: "labelled", pairs }];
}

function renderTopLevelSection(title: string, value: unknown): RenderNode {
  return {
    kind: "section",
    title,
    level: 1,
    children: renderValue(value, 2),
  };
}

function renderValue(value: unknown, level: number): RenderNode[] {
  if (value == null) return [];
  if (typeof value === "string") {
    return [{ kind: "paragraph", text: value }];
  }
  if (typeof value === "number" || typeof value === "boolean") {
    return [{ kind: "paragraph", text: String(value) }];
  }
  if (Array.isArray(value)) {
    return renderArray(value, level);
  }
  if (typeof value === "object") {
    return renderObject(value as Record<string, unknown>, level);
  }
  return [];
}

function renderArray(arr: unknown[], level: number): RenderNode[] {
  if (arr.length === 0) {
    return [{ kind: "paragraph", text: "(none recorded)" }];
  }
  if (arr.every((x) => typeof x === "string")) {
    return [{ kind: "list", items: alphaItems(arr as string[]) }];
  }
  // Array of objects → labelled subsections.
  const children: RenderNode[] = [];
  arr.forEach((item, i) => {
    children.push({
      kind: "section",
      title: `Entry ${i + 1}`,
      level,
      children: renderValue(item, level + 1),
    });
  });
  return children;
}

function renderObject(
  obj: Record<string, unknown>,
  level: number,
): RenderNode[] {
  const out: RenderNode[] = [];
  for (const [key, value] of Object.entries(obj)) {
    const title = humanise(key);
    out.push({
      kind: "section",
      title,
      level,
      children: renderValue(value, level + 1),
    });
  }
  return out;
}

function humanise(key: string): string {
  return key
    .split("_")
    .map((w, i) => (i === 0 ? capitalise(w) : w))
    .join(" ");
}

function capitalise(s: string): string {
  if (!s) return s;
  return s[0].toUpperCase() + s.slice(1);
}

/**
 * Wrap items in EU drafting-style `(a) X; (b) Y; (c) Z.`. We pass through the
 * raw strings here and let the renderer compose them — but the formatter is
 * exported so callers can reuse the same string in plain-text contexts.
 */
function alphaItems(items: string[]): string[] {
  // Stored as already-prefixed strings so each renderer can simply render them
  // line-by-line and the EU formatting carries through DOCX, HTML, and PDF.
  const composed = formatAlphaList(items, { separator: "\n" });
  return composed.split("\n");
}
