import { PDFDocument, StandardFonts, rgb, type PDFFont, type PDFPage } from "pdf-lib";
import type { RenderDoc, RenderNode } from "./ir.js";

const PAGE_W = 595.28;
const PAGE_H = 841.89; // A4 in points
const MARGIN = 64;
const LINE_GAP = 4;

interface Cursor {
  page: PDFPage;
  y: number;
}

export async function renderPdf(doc: RenderDoc): Promise<Uint8Array> {
  const pdf = await PDFDocument.create();
  pdf.setTitle(doc.title);
  pdf.setSubject(doc.subtitle);
  pdf.setCreator(`actcheck ${doc.toolVersion}`);
  pdf.setProducer(`actcheck ${doc.toolVersion}`);
  pdf.setCreationDate(new Date(doc.generatedAt));

  const sans = await pdf.embedFont(StandardFonts.Helvetica);
  const sansBold = await pdf.embedFont(StandardFonts.HelveticaBold);

  const cursor: Cursor = { page: addPage(pdf), y: PAGE_H - MARGIN };

  drawTitle(cursor, pdf, sansBold, doc.title);
  drawSubtitle(cursor, pdf, sans, doc.subtitle);
  drawHairline(cursor);

  for (const node of doc.cover) {
    drawNode(cursor, pdf, sans, sansBold, node);
  }

  for (const node of doc.body) {
    drawNode(cursor, pdf, sans, sansBold, node);
  }

  drawHairline(cursor);
  drawWrapped(
    cursor,
    pdf,
    sans,
    9,
    `Generated by actcheck ${doc.toolVersion} on ${doc.generatedAt}.`,
  );
  if (doc.retention) {
    drawWrapped(
      cursor,
      pdf,
      sans,
      9,
      `Article 18(1) retention obligation: ${doc.retention.placedOnMarket} -> ${doc.retention.retentionUntil}.`,
    );
  }

  return pdf.save();
}

/**
 * Standard Helvetica in pdf-lib uses WinAnsi (CP-1252), which can't encode
 * characters like → ↔ … ✓ ✗. Map the ones we actually emit to ASCII
 * equivalents so the PDF renderer never crashes on user input.
 */
function sanitizeWinAnsi(text: string): string {
  return text
    .replace(/→/g, "->")
    .replace(/←/g, "<-")
    .replace(/↔/g, "<->")
    .replace(/⇒/g, "=>")
    .replace(/…/g, "...")
    .replace(/✓/g, "v")
    .replace(/✗/g, "x")
    .replace(/⚠/g, "!")
    .replace(/·/g, "-")
    // Strip anything else still outside WinAnsi (rare, but defensive).
    .replace(/[^\x00-\xFF]/g, "?");
}

function addPage(pdf: PDFDocument): PDFPage {
  return pdf.addPage([PAGE_W, PAGE_H]);
}

function ensureRoom(cursor: Cursor, pdf: PDFDocument, needed: number): void {
  if (cursor.y - needed >= MARGIN) return;
  cursor.page = addPage(pdf);
  cursor.y = PAGE_H - MARGIN;
}

function drawTitle(
  cursor: Cursor,
  pdf: PDFDocument,
  font: PDFFont,
  text: string,
): void {
  ensureRoom(cursor, pdf, 30);
  cursor.page.drawText(sanitizeWinAnsi(text), {
    x: MARGIN,
    y: cursor.y - 20,
    size: 18,
    font,
    color: rgb(0.12, 0.31, 0.47),
  });
  cursor.y -= 26;
}

function drawSubtitle(
  cursor: Cursor,
  pdf: PDFDocument,
  font: PDFFont,
  text: string,
): void {
  ensureRoom(cursor, pdf, 18);
  cursor.page.drawText(sanitizeWinAnsi(text), {
    x: MARGIN,
    y: cursor.y - 14,
    size: 11,
    font,
    color: rgb(0.4, 0.43, 0.48),
  });
  cursor.y -= 22;
}

function drawHairline(cursor: Cursor): void {
  cursor.page.drawLine({
    start: { x: MARGIN, y: cursor.y },
    end: { x: PAGE_W - MARGIN, y: cursor.y },
    color: rgb(0.84, 0.86, 0.88),
    thickness: 0.5,
  });
  cursor.y -= 12;
}

function drawNode(
  cursor: Cursor,
  pdf: PDFDocument,
  sans: PDFFont,
  sansBold: PDFFont,
  node: RenderNode,
): void {
  switch (node.kind) {
    case "section": {
      const size = sectionSize(node.level);
      ensureRoom(cursor, pdf, size + 8);
      cursor.page.drawText(sanitizeWinAnsi(node.title), {
        x: MARGIN,
        y: cursor.y - size,
        size,
        font: sansBold,
        color: rgb(0.12, 0.31, 0.47),
      });
      cursor.y -= size + 8;
      for (const child of node.children) drawNode(cursor, pdf, sans, sansBold, child);
      cursor.y -= 4;
      break;
    }
    case "paragraph":
      drawWrapped(cursor, pdf, sans, 10, node.text);
      break;
    case "list": {
      for (const item of node.items) {
        drawWrapped(cursor, pdf, sans, 10, item);
      }
      break;
    }
    case "labelled":
      for (const p of node.pairs) {
        const label = `${p.label}: `;
        const safeLabel = sanitizeWinAnsi(label);
        const safeValue = sanitizeWinAnsi(p.value);
        const labelWidth = sansBold.widthOfTextAtSize(safeLabel, 10);
        ensureRoom(cursor, pdf, 14);
        cursor.page.drawText(safeLabel, {
          x: MARGIN,
          y: cursor.y - 10,
          size: 10,
          font: sansBold,
          color: rgb(0.16, 0.18, 0.22),
        });
        // Render the value on the same line if it fits, else wrap below.
        const valueWidth = sans.widthOfTextAtSize(safeValue, 10);
        if (labelWidth + valueWidth < PAGE_W - 2 * MARGIN) {
          cursor.page.drawText(safeValue, {
            x: MARGIN + labelWidth,
            y: cursor.y - 10,
            size: 10,
            font: sans,
            color: rgb(0.06, 0.07, 0.09),
          });
          cursor.y -= 12 + LINE_GAP;
        } else {
          cursor.y -= 12;
          drawWrapped(cursor, pdf, sans, 10, p.value);
        }
      }
      cursor.y -= 4;
      break;
  }
}

function sectionSize(level: number): number {
  const map: Record<number, number> = { 1: 14, 2: 12, 3: 11, 4: 10.5, 5: 10, 6: 10 };
  return map[Math.min(6, Math.max(1, level))] ?? 11;
}

function drawWrapped(
  cursor: Cursor,
  pdf: PDFDocument,
  font: PDFFont,
  size: number,
  text: string,
): void {
  const maxWidth = PAGE_W - 2 * MARGIN;
  const words = text.split(/\s+/).filter(Boolean);
  let line = "";
  for (const word of words) {
    const candidate = line ? `${line} ${word}` : word;
    if (font.widthOfTextAtSize(candidate, size) > maxWidth) {
      flushLine(cursor, pdf, font, size, line);
      line = word;
    } else {
      line = candidate;
    }
  }
  if (line) flushLine(cursor, pdf, font, size, line);
}

function flushLine(
  cursor: Cursor,
  pdf: PDFDocument,
  font: PDFFont,
  size: number,
  line: string,
): void {
  ensureRoom(cursor, pdf, size + LINE_GAP);
  cursor.page.drawText(sanitizeWinAnsi(line), {
    x: MARGIN,
    y: cursor.y - size,
    size,
    font,
    color: rgb(0.06, 0.07, 0.09),
  });
  cursor.y -= size + LINE_GAP;
}
